"""initial schema

Revision ID: bea1942db596
Revises: 
Create Date: 2026-06-21 13:54:09.081903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea1942db596'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('broker', sa.String(length=64), nullable=True),
    sa.Column('funding_bucket', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('opened', sa.Date(), nullable=True),
    sa.Column('closed', sa.Date(), nullable=True),
    sa.CheckConstraint("funding_bucket in ('cash','cpf','srs')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fx_rate',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_to_sgd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('date', 'currency')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rows_in', sa.Integer(), nullable=False),
    sa.Column('rows_new', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uq_batch_filehash')
    )
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_ticker', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=True),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_ticker')
    )
    op.create_table('corporate_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('from_ticker', sa.String(length=24), nullable=True),
    sa.Column('to_ticker', sa.String(length=24), nullable=True),
    sa.Column('ratio_num', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ratio_den', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('amount_per_unit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('units', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('gross', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('withholding_tax', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_file', sa.String(length=256), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_div_dedup')
    )
    op.create_index(op.f('ix_dividend_pay_date'), 'dividend', ['pay_date'], unique=False)
    op.create_table('position_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'security_id', 'date', 'source', name='uq_snapshot')
    )
    op.create_index(op.f('ix_position_snapshot_date'), 'position_snapshot', ['date'], unique=False)
    op.create_table('price',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'date')
    )
    op.create_table('security_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', name='uq_alias')
    )
    op.create_table('txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('settle_date', sa.Date(), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('qty_signed', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('fees', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('funding_bucket', sa.String(length=8), nullable=True),
    sa.Column('source_file', sa.String(length=256), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_txn_dedup')
    )
    op.create_index(op.f('ix_txn_trade_date'), 'txn', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_txn_trade_date'), table_name='txn')
    op.drop_table('txn')
    op.drop_table('security_alias')
    op.drop_table('price')
    op.drop_index(op.f('ix_position_snapshot_date'), table_name='position_snapshot')
    op.drop_table('position_snapshot')
    op.drop_index(op.f('ix_dividend_pay_date'), table_name='dividend')
    op.drop_table('dividend')
    op.drop_table('corporate_action')
    op.drop_table('security')
    op.drop_table('import_batch')
    op.drop_table('fx_rate')
    op.drop_table('account')
    # ### end Alembic commands ###
